### PR TITLE
Fix/doc links

### PR DESCRIPTION
**Pull request by danieleades**
fixes some broken links in the doc comments

### CODE REVIEW

**Comment by danieleades** [comment]
there's a bit more to do. there's a lot of references in the code to a `PersistentEvent`, but i can't see that anywhere. Is that a reference from an earlier API version perhaps?

**Comment by ar3s3ru** [comment]
Hey there, thanks for the PR! Really appreciated the love for docs, I admit I left those behind a bit 😅 

> there's a bit more to do. there's a lot of references in the code to a `PersistentEvent`, but i can't see that anywhere. Is that a reference from an earlier API version perhaps?

It should be [`eventually_core::store::Persisted`](https://github.com/get-eventually/eventually-rs/blob/2b08cc60e164244e2782e6fdbaaeccee414dfb00/eventually-core/src/store.rs#L178-L193)

**Comment by danieleades** [comment]
by the way, i'm assuming a squash merge in these pull requests. unless you'd rather i rebased?

**Comment by danieleades** [comment]
the nightly linting thing probably belongs in a separate pull request, happy to roll that one back @ar3s3ru

**Comment by ar3s3ru** [comment]
>by the way, i'm assuming a squash merge in these pull requests. unless you'd rather i rebased?

Squash-merges are the only merge operations enabled on this repository 😄 ✌🏻 

> the nightly linting thing probably belongs in a separate pull request, happy to roll that one back @ar3s3ru

Yes that would be best 👍🏻

**Review by ar3s3ru — APPROVED** [review]

**Pull request merged**
