### PR TITLE
Allow anything that can be stringed for type_name

### PR DESCRIPTION
**Pull request by to266**
Hi, just another quick PR to allow anything which can be turned into a `String` for the `type_name` in the postgres.

As it is currently, the requirement for `&'static str` prevents from generating these names in code from configuration (and I want **that** because the names are also used for channels in the NOTIFY/LISTEN - if multiple deployments on the same DB are to not clash, they have to have different channel names, otherwise data is leaked / shared)

### CODE REVIEW

**Review by ar3s3ru — COMMENTED** [review]
Hi @to266, glad to see you back! 😄 

Thank you for the PR, as always ❤️ 

Before approving, I want to understand a bit more your use case, as it looks a bit unusual to me. At the same time, let me briefly explain the reason why `type_name` is currently a `&'static str`.

The current `eventually::EventStore` trait works by referencing a single Event Stream type, and this type is -- in the context of Event Sourcing -- an Aggregate.

Take the example of a Bank Account: the type name of the Aggregate is `BankAccount`. In a typical web app using an RDBMS, you'll most likely insert the state of the Aggregate inside a `bank_accounts` table, right?

Well, the `type_name` has the exact same function: in a way, it kinda represents the "table name" of your Aggregate. That's why it's a `&'static str`: a `BankAccount` is a `BankAccount`. Configuration doesn't change that, because the name comes from the Domain.

I'm not sure of your use-case -- again, would love to hear more about it -- but it feels like you're trying to treat the `type_name` parameter as a sharding parameter, so that multiple deployments of the same application would write to "different shards" of the Event Store data to enforce data segregation.

If that's the case, have you considered:
1. Include this "sharding" parameter into your Aggregate ID?
2. Have multiple databases in the same database instance? (AFAIK you can use `CREATE DATABASE`, this is a way safer strategy if data segregation is a strict requirement)

**Comment by to266** [comment]
Yeah, I know that the `type_name` comes from Domain and how it all interacts in ES lingo :smiley: 

The real goal of the PR is to allow customization of the NOTIFY/LISTEN channels, not Aggregate names. It is simply due to the current design of `eventually` (and the fact that these channels are not part of the public interface, now that I think about it) that it effectively translates to being able to customize the names of the aggregates, which goes against the ES and DDD flow.

Overall, a better solution would be to make these LISTEN/NOTIFY channels part of the public interface - therefore allowing their customization. However that's somewhat larger undertaking than above :)

For reference, we chose to split the data via database schemas, because sharding parameter in the aggregate ID is not sufficiently isolated, while actually using separate databases is too restrictive, as there is (or will be) "public" schema that should be accessible by simply using a fully-qualified table name.

**Comment by ar3s3ru** [comment]
>because sharding parameter in the aggregate ID is not sufficiently isolated

Why is that?

Here I'm thinking about how you would solve this same problem with a commercial event store, say [EventStore](https://www.eventstore.com/), and the only way I can think of is through different Event Streams, and this can be implemented in different ways depending on the level of "data sharing" that your use case needs:

1. If the data needs no sharing whatsoever, then you can just create separate Event Streams (similar to your approach here) but in case of "joins" you can project multiple Event Streams to another Event Stream.
1. If the data might need some sharing, as in some projections that might span through this "sharding key", it might be better to use the same Event Stream category (or here, type) but include the sharding key in the Event Stream name to differentiate (e.g. category `accounts`, sharding keys `deposit` / `saving`, streams `accounts:deposit:abcd123`, `accounts:saving:abcd123` -- then you can subscribe to all `deposit` events using `accounts:deposit` and all `saving` events using `accounts:saving`, and all events using `accounts`)

Anyway, given case 1. using `type_name` as a `String` might be reasonable, just trying to think whether this "liberty" might cause accidental misuse 😅

**Comment by to266** [comment]
Yeah, sorry for bringing up the "public" schema altogether - this is related to the data that is not event-sourced at all, and has nothing to do with `eventually`, so just brings more confusion.

As for the data sharing, we are very certain that we'll not need it. In fact the whole goal is to prevent it in the first place, while making it as difficult to do by mistake as possible - while still using the same database. Going with your example, the separation is not between `accounts` or `deposit`/`savings`. In our case it's the separation between different banks altogether. Since each user would have a unique account ID you **could** do it, but it might be difficult explaining that to the bank, and making the mistake of leaking the data between banks is not difficult

**Comment by ar3s3ru** [comment]
Hey @to266,
sorry for disappearing on you 😢 

>As for the data sharing, we are very certain that we'll not need it. In fact the whole goal is to prevent it in the first place, while making it as difficult to do by mistake as possible

Using separate databases still looks like a good idea to me, given that you should treat them as Event Streams, and you can always combine Event Streams together, even if coming from different data sources.

But let's say you don't quite like this approach, and you'd rather have every Event Stream in the same Event Store. 

Another approach that doesn't require to change aggregate type name dynamically is to enforce some filtering on the Event Store itself, when reading. This could work with some sort of zero-cost abstraction (maybe using newtype pattern):

```rust
// NOTE: not sure this code compiles, just writing something to get the point across :D

pub struct FilteredEventStore<F, ES> {
    criteria: F,
    inner: ES
}

impl<F, ES> EventStore for FilteredEventStore<F, ES> {
     // ...
    fn stream(&self) -> EventStream {
        self.inner
            .stream()
            .filter(|event| self.criteria(event)) // filter all events using the provided criteria
    }
}

// You can use it by decorating the default event store instance
let event_store = FilteredEventStore::new(event_store, |event| {
   event.source_id.bank == "my_bank" // here you could pass the String coming from the config 
});
```

---

I'm not _totally_ opposed to this change, but this one is a tricky one:
1. `v0.5.0`, which is going to have some drastic changes to the API, is going to use the `&'static str` a bit more predominantly, and [coming from the `Aggregate` itself](https://github.com/eventually-rs/eventually-rs/blob/b1d87225859a9285d3a323d8bb055b3fcb8eac38/eventually/src/aggregate.rs#L18), instead of being an EventStore-only concern. It could be supplied to the `Repository` itself, though... ([eventually-go already does this](https://github.com/eventually-rs/eventually-go/blob/78cdba7daef7b45f5b6e323bdb2776548ed79703/aggregate/repository.go#L20-L23), but mainly because Go doesn't have static methods)
2. If we were to change this in `eventually-postgres`, I want to keep it a consistent API choice everywhere, which means potentially change `eventually-redis` too, if needed be.

Any thoughts? 😄

**Comment by cortopy** [comment]
I'm guessing this PR is stale now, but I thought I'd drop a comment

I've also bumped into a similar case as this one today. I needed to pass a String in the tests for the `type_name` and I couldn't. I can see cases in which I may need that too in real code, and others in which I won't.

For this, I'm using my own version which does:

```rust
#[derive(Debug, Clone)]
pub struct EventStore<Event> {
    pub(crate) type_name: Cow<'static, str>,
    pool: PgPool,
    payload: std::marker::PhantomData<Event>,
}
```

`Cow` seems to be an excellent pointer which would cater for every case while keeping mem allocation to the bare minimum and only when it's needed

**Comment by ar3s3ru** [comment]
Hey @cortopy, the PR is stale at the moment yes.

I'm still a bit skeptical about the need for this change (maybe you can explain your use-case better?) but we can keep that in mind for when we start with `0.5.0` 👍🏻 

Maybe I should create a separate issue for this one, instead of keeping this PR open indefinitely 😅

**Pull request closed without merging**
