### PR TITLE
add MSRV

### PR DESCRIPTION
**Pull request by danieleades**
this is a pretty significant overhaul of the CI jobs, so i don't expect this will be merged without some discussion.

The primary goal was to introduce a check of the "minimum stable rust version" (MSRV). This check ensures that any dependency or syntax which caused the minimum compiler version to increase is caught, and can therefore result in a semver bump. usually a MSRV bump will cause a patch change pre 1.0, and a minor change post 1.0 (but there's no *firmly* agreed convention)

I've also split the coverage into a separate workflow, so that "blocking quality gates" live in one workflow, and "informational" jobs live in the other. Not sure how you feel about that.

the clippy config file ensures that you don't get lints for new syntax that was introduced *after* the MSRV

### CODE REVIEW

**Comment by danieleades** [comment]
one caveat- if you're using 'expected jobs' you need to change the name of the job manually every time you bump the MSRV. that's a bit annoying. there's a workaround, which is to explicitly name the matrix jobs, but it's a lot more verbose. looks like this - https://github.com/danieleades/monzo-lib/blob/2c4565c1ac9b78c5aaa5a784f6417fc9f845ede5/.github/workflows/CI.yml#L15-L33

**Review by ar3s3ru — COMMENTED** [review]
Hey @danieleades, awesome stuff! I would like to name the MSVR so that I don't need to make extra changes to the "expected jobs". Would you take care of that? 🙏🏻 

Thanks again for the PR, this is great 😄

**Comment by danieleades** [comment]
> Hey @danieleades, awesome stuff! I would like to name the MSVR so that I don't need to make extra changes to the "expected jobs". Would you take care of that? 🙏🏻
> 
> Thanks again for the PR, this is great 😄

done.

you'll still need to change the 'expected job's *once*

**Comment by ar3s3ru** [comment]
Noice! Thanks a lot 😄

**Pull request merged**
