### PR TITLE
migrate to 2021 edition

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by danieleades** [comment]
clippy workflow blocked on #189

**Comment by ar3s3ru** [comment]
Wouldn't this PR break projects that are not using 2021 version?

**Comment by danieleades** [comment]
> Wouldn't this PR break projects that are not using 2021 version?

no, projects don't need to be on the same edition as their dependencies. It *will* break any project using a toolchain less than 1.56 (hence the MSRV bump). The current stable version is 1.56.1.

**Review by ar3s3ru — APPROVED** [review]
LGTM 🚀

**Pull request merged**
