### PR TITLE
update coverage workflow

### PR DESCRIPTION
**Pull request by danieleades**
`llvm-cov` is better maintained, and supports doc-tests coverage

### CODE REVIEW

**Comment by danieleades** [comment]
@ar3s3ru how attached are you to the `cobertura.xml` format? what do you use the archived coverage reports for?

**Review by ar3s3ru — COMMENTED** [review]
Hey @danieleades, welcome back!

Not particularly attached to any specific format.
However, couple of things:
* I would stay on `stable` to generate coverage; if a tool does not work on stable, I don't think we should use it yet honestly,
* `cargo-tarpaulin` is still pretty active, and seems to me a more stable project than `cargo-llvm-cov` (also, supports `llvm` backend); any specific reason to change to that solution? I may be missing some context (not very active in the overall Rust ecosystem).

**Comment by danieleades** [comment]
> * I would stay on `stable` to generate coverage; if a tool does not work on stable, I don't think we should use it yet honestly,

I don't think there's any reason to avoid using the nightly compiler in CI. If you're really worried you can pin to a specific version of the nightly compiler. What problems are you trying to avoid by not using the nightly compiler in CI?
`cargo-llvm-cov` itself is not unstable, nor does it need nightly for its core feature set. It relies on nightly compiler features to produce coverage for doctests. tarpaulin doesn't support doc test coverage at all.

> * `cargo-tarpaulin` is still pretty active, and seems to me a more stable project than `cargo-llvm-cov` (also, supports `llvm` backend); any specific reason to change to that solution? I may be missing some context (not very active in the overall Rust ecosystem).

llvm-cov is  a much simpler implementation, has been stable for years. Anecdotally it produces much more accurate coverage information. Tarpaulin *does* now support the LLVM-based coverage, but this is brand spanking new (as in, in the last couple of months. the tracking issue is still open).

**Comment by danieleades** [comment]
> > What problems are you trying to avoid by not using the nightly compiler in CI?
> 
> `nightly` breaks unexpectedly, as it actually did while I was developing some stuff. Had to disable nightly merge check in the pipeline to make it pass CI (context: [67ed3d2](https://github.com/get-eventually/eventually-rs/commit/67ed3d2cd9c85f0b0949dedadc17e3bb52a31d9e)).
> 
> So I honestly prefer making coverage running in `stable` a strong requirement.

It sounds like pinning to a specific nightly version might be the most appropriate solution

> 
> In the case of `cargo-llvm-cov` it seems not to be a huge deal, since I don't think we have many doctests here (or none at all actually), so I can live with it running in `stable`.

That's true, but there's also a massive amount of clippy warnings about the lack of documentation...
Having the doctests coverage in place means you can see the impact on coverage as doctests/examples are added!

> 
> And thank you for the context on Tarpaulin. Seems like I have some digging around to do to get more context. I'll get back to this PR once I do that.

no worries. My own experience with tarpaulin is that it works, and the maintaineris very responsive, but it relies on a lot of undocumented or unspecified cargo/rustc features and is therefore very brittle.

**Comment by ar3s3ru** [comment]
Seems like `tarpaulin` is creating issues in CI, so I'm looking at this PR again (sorry, these long hiatuses mean stressful days at work 😅).

Would you be ok to change to `stable` toolchain, as we discussed above?
As I said, we don't have many doctests now so I'd be ok with having it running without it.

If you cannot make the change, I hope it's ok if I make the change myself and merge the PR 😄

**Pull request merged**
