### PR TITLE
simplify 'EventStore' trait

### PR DESCRIPTION
**Pull request by danieleades**
i've marked this as a draft for now, since it doesn't have parity with the original implementation- I've stripped out some of the `tracing` from the original and not replaced it in this implementation. It wasn't totally clear to me where it should go, so i might need some input.

while i was doing it i thought that maybe implementing tracing in the trait implementation maybe isn't the best place for it anyway. It would be better if the logging was added to the code that calls the trait, so that the logging is unified and consistent regardless of the actual implementation of the trait. Interested to hear your thoughts

### CODE REVIEW

**Comment by danieleades** [comment]
more "spurious network errors"...

**Comment by cortopy** [comment]
@danieleades  I'm just doing my first dip into eventually. I think it's awesome! thank you for that

I was looking at what changes may come with 0.5. Since you mention the removal of tracing, IMO the tracing crate is one of my top 10 crates in Rust ecosystem. Those that don't use it wouldn't lose anything by having it, and those that use it will lose some tracing. I find it particularly useful for debugging networking issues (e.g.: EventStore disconnections, etc.)

**Comment by cortopy** [comment]
I misread your comment then. Thanks for that!

**Review by ar3s3ru — COMMENTED** [review]
Hey @danieleades, thanks for the PR!

I would like to merge this with the changes to `tracing` instrumentation figured out. Maybe we can add some extension trait to `eventually-util` for `EventStore`, that enables the `tracing` instrumentation?

For `eventually-util` and `eventually`, we could use a feature flag to enable in this feature. Wdyt?

**Comment by danieleades** [comment]
> Hey @danieleades, thanks for the PR!
> 
> I would like to merge this with the changes to `tracing` instrumentation figured out. Maybe we can add some extension trait to `eventually-util` for `EventStore`, that enables the `tracing` instrumentation?
> 
> For `eventually-util` and `eventually`, we could use a feature flag to enable in this feature. Wdyt?

There's two ways you could do it, i think

- wrap the `EventStore` in a struct which delegates all the methods, but instruments them with tracing. This could be an entirely crate-private struct, so no change to public API.
- Add tracing in all the places where the `EventStore` methods are actually called

In either case you could make 'tracing' an optional dep without too much effort

**Comment by ar3s3ru** [comment]
> wrap the `EventStore` in a struct which delegates all the methods, but instruments them with tracing. This could be an entirely crate-private struct, so no change to public API.

This is what I would do, yes.

What's more, I would make this struct public and add a supertrait to `EventStore` with an `instrumented(self)` method that returns the instrumented struct instance of itself. Wdyt?

**Comment by danieleades** [comment]
> > wrap the `EventStore` in a struct which delegates all the methods, but instruments them with tracing. This could be an entirely crate-private struct, so no change to public API.
> 
> This is what I would do, yes.
> 
> What's more, I would make this struct public and add a supertrait to `EventStore` with an `instrumented(self)` method that returns the instrumented struct instance of itself. Wdyt?

this approach will require adding `Debug` or `Display` bounds to the `EventStore` associated types. is that acceptable?

**Comment by ar3s3ru** [comment]
Feel free to give it a try and see where we end up 😄

**Comment by ar3s3ru** [comment]
Closing this as the v0.5.0 version (#192) superseded it :v:

**Pull request closed without merging**
